"""initial

Revision ID: 00001
Revises:
Create Date: 2023-11-26 12:01:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "00001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Games",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_name", sa.String(), nullable=False),
        sa.Column("game_description", sa.String(), nullable=False),
        sa.Column("game_ranks", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("game_logo", sa.String(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("update_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_Games_create_date"), "Games", ["create_date"], unique=False
    )
    op.create_index(op.f("ix_Games_game_name"), "Games", ["game_name"], unique=True)
    op.create_index(op.f("ix_Games_id"), "Games", ["id"], unique=True)
    op.create_index(
        op.f("ix_Games_update_date"), "Games", ["update_date"], unique=False
    )
    op.create_table(
        "Rooms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("room_name", sa.String(), nullable=False),
        sa.Column("room_description", sa.String(), nullable=True),
        sa.Column("room_ranks", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("room_size", sa.Integer(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("update_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_Rooms_create_date"), "Rooms", ["create_date"], unique=False
    )
    op.create_index(op.f("ix_Rooms_game_id"), "Rooms", ["game_id"], unique=False)
    op.create_index(op.f("ix_Rooms_id"), "Rooms", ["id"], unique=True)
    op.create_index(op.f("ix_Rooms_owner_id"), "Rooms", ["owner_id"], unique=False)
    op.create_index(op.f("ix_Rooms_room_name"), "Rooms", ["room_name"], unique=False)
    op.create_index(
        op.f("ix_Rooms_update_date"), "Rooms", ["update_date"], unique=False
    )
    op.create_table(
        "Users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("password_timestamp", sa.Float(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("update_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_Users_create_date"), "Users", ["create_date"], unique=False
    )
    op.create_index(op.f("ix_Users_id"), "Users", ["id"], unique=True)
    op.create_index(op.f("ix_Users_room_id"), "Users", ["room_id"], unique=False)
    op.create_index(
        op.f("ix_Users_update_date"), "Users", ["update_date"], unique=False
    )
    op.create_index(op.f("ix_Users_username"), "Users", ["username"], unique=True)
    op.create_table(
        "Profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("user_nickname", sa.String(), nullable=True),
        sa.Column("user_rank", sa.String(), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("update_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", "user_id", "game_id"),
        sa.UniqueConstraint("user_id", "game_id", name="user_game"),
    )
    op.create_index(
        op.f("ix_Profiles_create_date"), "Profiles", ["create_date"], unique=False
    )
    op.create_index(op.f("ix_Profiles_game_id"), "Profiles", ["game_id"], unique=False)
    op.create_index(op.f("ix_Profiles_id"), "Profiles", ["id"], unique=True)
    op.create_index(
        op.f("ix_Profiles_update_date"), "Profiles", ["update_date"], unique=False
    )
    op.create_index(op.f("ix_Profiles_user_id"), "Profiles", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Profiles_user_id"), table_name="Profiles")
    op.drop_index(op.f("ix_Profiles_update_date"), table_name="Profiles")
    op.drop_index(op.f("ix_Profiles_id"), table_name="Profiles")
    op.drop_index(op.f("ix_Profiles_game_id"), table_name="Profiles")
    op.drop_index(op.f("ix_Profiles_create_date"), table_name="Profiles")
    op.drop_table("Profiles")
    op.drop_index(op.f("ix_Users_username"), table_name="Users")
    op.drop_index(op.f("ix_Users_update_date"), table_name="Users")
    op.drop_index(op.f("ix_Users_room_id"), table_name="Users")
    op.drop_index(op.f("ix_Users_id"), table_name="Users")
    op.drop_index(op.f("ix_Users_create_date"), table_name="Users")
    op.drop_table("Users")
    op.drop_index(op.f("ix_Rooms_update_date"), table_name="Rooms")
    op.drop_index(op.f("ix_Rooms_room_name"), table_name="Rooms")
    op.drop_index(op.f("ix_Rooms_owner_id"), table_name="Rooms")
    op.drop_index(op.f("ix_Rooms_id"), table_name="Rooms")
    op.drop_index(op.f("ix_Rooms_game_id"), table_name="Rooms")
    op.drop_index(op.f("ix_Rooms_create_date"), table_name="Rooms")
    op.drop_table("Rooms")
    op.drop_index(op.f("ix_Games_update_date"), table_name="Games")
    op.drop_index(op.f("ix_Games_id"), table_name="Games")
    op.drop_index(op.f("ix_Games_game_name"), table_name="Games")
    op.drop_index(op.f("ix_Games_create_date"), table_name="Games")
    op.drop_table("Games")
    # ### end Alembic commands ###
