"""relations

Revision ID: 00002
Revises:
Create Date: 2023-11-26 12:02:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "00002"
down_revision = "00001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "Profiles", "Users", ["user_id"], ["id"])
    op.create_foreign_key(None, "Profiles", "Games", ["game_id"], ["id"])
    op.create_foreign_key(None, "Rooms", "Games", ["game_id"], ["id"])
    op.create_foreign_key(None, "Rooms", "Users", ["owner_id"], ["id"])
    op.create_foreign_key(None, "Users", "Rooms", ["room_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Users", type_="foreignkey")
    op.drop_constraint(None, "Rooms", type_="foreignkey")
    op.drop_constraint(None, "Rooms", type_="foreignkey")
    op.drop_constraint(None, "Profiles", type_="foreignkey")
    op.drop_constraint(None, "Profiles", type_="foreignkey")
    # ### end Alembic commands ###
